export enum AuthTypes {
    LOGIN_START = '[AUTH] LOGIN_START',
    LOGIN_SUCCESS = '[AUTH] LOGIN_SUCCESS',
    AUTO_LOGIN = '[AUTH] AUTO_LOGIN',
    REGISTER_START = '[AUTH] REGISTER_START',
    REGISTER_SUCCESS = '[AUTH] REGISTER_SUCCESS',
    LOGOUT = '[AUTH] LOGOUT',
    THROW_ERROR = '[AUTH] THROW_ERROR'
};